//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.BLL.CreditCardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfo", Namespace="http://schemas.datacontract.org/2004/07/CreditCardService.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecureCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationMonth {
            get {
                return this.ExpirationMonthField;
            }
            set {
                if ((this.ExpirationMonthField.Equals(value) != true)) {
                    this.ExpirationMonthField = value;
                    this.RaisePropertyChanged("ExpirationMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationYear {
            get {
                return this.ExpirationYearField;
            }
            set {
                if ((this.ExpirationYearField.Equals(value) != true)) {
                    this.ExpirationYearField = value;
                    this.RaisePropertyChanged("ExpirationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecureCode {
            get {
                return this.SecureCodeField;
            }
            set {
                if ((this.SecureCodeField.Equals(value) != true)) {
                    this.SecureCodeField = value;
                    this.RaisePropertyChanged("SecureCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/CreditCardService.Static")]
    public enum PaymentStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotExistedCard = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmationRequired = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmationStatus", Namespace="http://schemas.datacontract.org/2004/07/CreditCardService.Static")]
    public enum ConfirmationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successfull = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aborted = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditCardService.ICreditCardService")]
    public interface ICreditCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/PayVisa", ReplyAction="http://tempuri.org/ICreditCardService/PayVisaResponse")]
        GameStore.BLL.CreditCardService.PaymentStatus PayVisa(GameStore.BLL.CreditCardService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/PayVisa", ReplyAction="http://tempuri.org/ICreditCardService/PayVisaResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.PaymentStatus> PayVisaAsync(GameStore.BLL.CreditCardService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/PayMasterCard", ReplyAction="http://tempuri.org/ICreditCardService/PayMasterCardResponse")]
        GameStore.BLL.CreditCardService.PaymentStatus PayMasterCard(GameStore.BLL.CreditCardService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/PayMasterCard", ReplyAction="http://tempuri.org/ICreditCardService/PayMasterCardResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.PaymentStatus> PayMasterCardAsync(GameStore.BLL.CreditCardService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/Confirm", ReplyAction="http://tempuri.org/ICreditCardService/ConfirmResponse")]
        GameStore.BLL.CreditCardService.ConfirmationStatus Confirm(string cardNumber, string confirmationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditCardService/Confirm", ReplyAction="http://tempuri.org/ICreditCardService/ConfirmResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.ConfirmationStatus> ConfirmAsync(string cardNumber, string confirmationCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditCardServiceChannel : GameStore.BLL.CreditCardService.ICreditCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardServiceClient : System.ServiceModel.ClientBase<GameStore.BLL.CreditCardService.ICreditCardService>, GameStore.BLL.CreditCardService.ICreditCardService {
        
        public CreditCardServiceClient() {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.BLL.CreditCardService.PaymentStatus PayVisa(GameStore.BLL.CreditCardService.PaymentInfo info) {
            return base.Channel.PayVisa(info);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.PaymentStatus> PayVisaAsync(GameStore.BLL.CreditCardService.PaymentInfo info) {
            return base.Channel.PayVisaAsync(info);
        }
        
        public GameStore.BLL.CreditCardService.PaymentStatus PayMasterCard(GameStore.BLL.CreditCardService.PaymentInfo info) {
            return base.Channel.PayMasterCard(info);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.PaymentStatus> PayMasterCardAsync(GameStore.BLL.CreditCardService.PaymentInfo info) {
            return base.Channel.PayMasterCardAsync(info);
        }
        
        public GameStore.BLL.CreditCardService.ConfirmationStatus Confirm(string cardNumber, string confirmationCode) {
            return base.Channel.Confirm(cardNumber, confirmationCode);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.CreditCardService.ConfirmationStatus> ConfirmAsync(string cardNumber, string confirmationCode) {
            return base.Channel.ConfirmAsync(cardNumber, confirmationCode);
        }
    }
}
