//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.WebUI.App_LocalResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.WebUI.App_LocalResources.Localization.ModelRes", typeof(ModelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AccountCountry {
            get {
                return ResourceManager.GetString("AccountCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string AccountDateOfBirth {
            get {
                return ResourceManager.GetString("AccountDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string AccountNewPassword {
            get {
                return ResourceManager.GetString("AccountNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat new password.
        /// </summary>
        public static string AccountNewPasswordRepeat {
            get {
                return ResourceManager.GetString("AccountNewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string AccountOldPassword {
            get {
                return ResourceManager.GetString("AccountOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AccountPassword {
            get {
                return ResourceManager.GetString("AccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string AccountPasswordRepeat {
            get {
                return ResourceManager.GetString("AccountPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role id.
        /// </summary>
        public static string AccountRoleId {
            get {
                return ResourceManager.GetString("AccountRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string AccountRoleName {
            get {
                return ResourceManager.GetString("AccountRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string AccountRoles {
            get {
                return ResourceManager.GetString("AccountRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string AccountUserId {
            get {
                return ResourceManager.GetString("AccountUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmationCode.
        /// </summary>
        public static string CardConfirmationCode {
            get {
                return ResourceManager.GetString("CardConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CommentContent {
            get {
                return ResourceManager.GetString("CommentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string CommentQuote {
            get {
                return ResourceManager.GetString("CommentQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CommentUserName {
            get {
                return ResourceManager.GetString("CommentUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian version of description.
        /// </summary>
        public static string GameDescriptionRu {
            get {
                return ResourceManager.GetString("GameDescriptionRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is discontinued.
        /// </summary>
        public static string GameDiscontinued {
            get {
                return ResourceManager.GetString("GameDiscontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by genres.
        /// </summary>
        public static string GameFilterGenres {
            get {
                return ResourceManager.GetString("GameFilterGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string GameFilterItemsPerPage {
            get {
                return ResourceManager.GetString("GameFilterItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal price.
        /// </summary>
        public static string GameFilterMaxPrice {
            get {
                return ResourceManager.GetString("GameFilterMaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal price.
        /// </summary>
        public static string GameFilterMinPrice {
            get {
                return ResourceManager.GetString("GameFilterMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of name.
        /// </summary>
        public static string GameFilterName {
            get {
                return ResourceManager.GetString("GameFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by platforms.
        /// </summary>
        public static string GameFilterPlatformTypes {
            get {
                return ResourceManager.GetString("GameFilterPlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by publication date.
        /// </summary>
        public static string GameFilterPublicationDate {
            get {
                return ResourceManager.GetString("GameFilterPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by publishers.
        /// </summary>
        public static string GameFilterPublishers {
            get {
                return ResourceManager.GetString("GameFilterPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string GameFilterSortByItems {
            get {
                return ResourceManager.GetString("GameFilterSortByItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game id.
        /// </summary>
        public static string GameGameId {
            get {
                return ResourceManager.GetString("GameGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game key.
        /// </summary>
        public static string GameGameKey {
            get {
                return ResourceManager.GetString("GameGameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game name.
        /// </summary>
        public static string GameGameName {
            get {
                return ResourceManager.GetString("GameGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string GameGenres {
            get {
                return ResourceManager.GetString("GameGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string GamePlatformTypes {
            get {
                return ResourceManager.GetString("GamePlatformTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GamePrice {
            get {
                return ResourceManager.GetString("GamePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        public static string GamePublicationDate {
            get {
                return ResourceManager.GetString("GamePublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string GamePublisher {
            get {
                return ResourceManager.GetString("GamePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt date.
        /// </summary>
        public static string GameReceiptDate {
            get {
                return ResourceManager.GetString("GameReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units in stock.
        /// </summary>
        public static string GameUnitsInStock {
            get {
                return ResourceManager.GetString("GameUnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GenreGenreName {
            get {
                return ResourceManager.GetString("GenreGenreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian version of name.
        /// </summary>
        public static string GenreGenreNameRu {
            get {
                return ResourceManager.GetString("GenreGenreNameRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string IboxAmount {
            get {
                return ResourceManager.GetString("IboxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoise number.
        /// </summary>
        public static string IboxInvoiseId {
            get {
                return ResourceManager.GetString("IboxInvoiseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string IboxOrderId {
            get {
                return ResourceManager.GetString("IboxOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationMethod.
        /// </summary>
        public static string NotificationInfoNotificationMethod {
            get {
                return ResourceManager.GetString("NotificationInfoNotificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string NotificationInfoTarget {
            get {
                return ResourceManager.GetString("NotificationInfoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string OrderCustomerId {
            get {
                return ResourceManager.GetString("OrderCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string OrderDetailsDiscount {
            get {
                return ResourceManager.GetString("OrderDetailsDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game key.
        /// </summary>
        public static string OrderDetailsProduct {
            get {
                return ResourceManager.GetString("OrderDetailsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetailsQuantity {
            get {
                return ResourceManager.GetString("OrderDetailsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string OrderOrderDetails {
            get {
                return ResourceManager.GetString("OrderOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string OrderOrderId {
            get {
                return ResourceManager.GetString("OrderOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order state.
        /// </summary>
        public static string OrderOrderState {
            get {
                return ResourceManager.GetString("OrderOrderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped date.
        /// </summary>
        public static string OrderShippedDate {
            get {
                return ResourceManager.GetString("OrderShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number (XXXX-XXXX-XXXX-XXXX).
        /// </summary>
        public static string PaymentCardNumber {
            get {
                return ResourceManager.GetString("PaymentCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        public static string PaymentCardType {
            get {
                return ResourceManager.GetString("PaymentCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration month.
        /// </summary>
        public static string PaymentExpirationMonth {
            get {
                return ResourceManager.GetString("PaymentExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration year.
        /// </summary>
        public static string PaymentExpirationYear {
            get {
                return ResourceManager.GetString("PaymentExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name and surname.
        /// </summary>
        public static string PaymentFullName {
            get {
                return ResourceManager.GetString("PaymentFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure code.
        /// </summary>
        public static string PaymentSecureCode {
            get {
                return ResourceManager.GetString("PaymentSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform type.
        /// </summary>
        public static string PlatformTypeName {
            get {
                return ResourceManager.GetString("PlatformTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string PublisherCompanyName {
            get {
                return ResourceManager.GetString("PublisherCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PublisherDescription {
            get {
                return ResourceManager.GetString("PublisherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian version of description.
        /// </summary>
        public static string PublisherDescriptionRu {
            get {
                return ResourceManager.GetString("PublisherDescriptionRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string PublisherHomePage {
            get {
                return ResourceManager.GetString("PublisherHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
