//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.WebUI.App_LocalResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfrastructureRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.WebUI.App_LocalResources.Localization.InfrastructureRes", typeof(InfrastructureRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string BanDay {
            get {
                return ResourceManager.GetString("BanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string BanHour {
            get {
                return ResourceManager.GetString("BanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month.
        /// </summary>
        public static string BanMonth {
            get {
                return ResourceManager.GetString("BanMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent.
        /// </summary>
        public static string BanPermanent {
            get {
                return ResourceManager.GetString("BanPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string BanWeek {
            get {
                return ResourceManager.GetString("BanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreatBritain.
        /// </summary>
        public static string CountryGreatBritain {
            get {
                return ResourceManager.GetString("CountryGreatBritain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string CountryRussia {
            get {
                return ResourceManager.GetString("CountryRussia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukraine.
        /// </summary>
        public static string CountryUkraine {
            get {
                return ResourceManager.GetString("CountryUkraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string CountryUsa {
            get {
                return ResourceManager.GetString("CountryUsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not issued.
        /// </summary>
        public static string OrderStateNotIssued {
            get {
                return ResourceManager.GetString("OrderStateNotIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not payed.
        /// </summary>
        public static string OrderStateNotPayed {
            get {
                return ResourceManager.GetString("OrderStateNotPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string OrderStatePayed {
            get {
                return ResourceManager.GetString("OrderStatePayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string OrderStateShipped {
            get {
                return ResourceManager.GetString("OrderStateShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Pagination_10 {
            get {
                return ResourceManager.GetString("Pagination_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string Pagination_100 {
            get {
                return ResourceManager.GetString("Pagination_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string Pagination_20 {
            get {
                return ResourceManager.GetString("Pagination_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string Pagination_50 {
            get {
                return ResourceManager.GetString("Pagination_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PaginationAll {
            get {
                return ResourceManager.GetString("PaginationAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string PaymentBank {
            get {
                return ResourceManager.GetString("PaymentBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote banking services.
        /// </summary>
        public static string PaymentBankDescription {
            get {
                return ResourceManager.GetString("PaymentBankDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBox.
        /// </summary>
        public static string PaymentIbox {
            get {
                return ResourceManager.GetString("PaymentIbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment network of Ukraine.
        /// </summary>
        public static string PaymentIboxDescription {
            get {
                return ResourceManager.GetString("PaymentIboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string PaymentVisa {
            get {
                return ResourceManager.GetString("PaymentVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American multinational financial services.
        /// </summary>
        public static string PaymentVisaDescription {
            get {
                return ResourceManager.GetString("PaymentVisaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 2 years.
        /// </summary>
        public static string PublicationDate2Years {
            get {
                return ResourceManager.GetString("PublicationDate2Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 years.
        /// </summary>
        public static string PublicationDate3Years {
            get {
                return ResourceManager.GetString("PublicationDate3Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PublicationDateAll {
            get {
                return ResourceManager.GetString("PublicationDateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string PublicationDateMonth {
            get {
                return ResourceManager.GetString("PublicationDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string PublicationDateWeek {
            get {
                return ResourceManager.GetString("PublicationDateWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string PublicationDateYear {
            get {
                return ResourceManager.GetString("PublicationDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition date.
        /// </summary>
        public static string SortingAdditionDate {
            get {
                return ResourceManager.GetString("SortingAdditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most commented.
        /// </summary>
        public static string SortingMostCommented {
            get {
                return ResourceManager.GetString("SortingMostCommented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular.
        /// </summary>
        public static string SortingMostPopular {
            get {
                return ResourceManager.GetString("SortingMostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SortingNone {
            get {
                return ResourceManager.GetString("SortingNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceAscending.
        /// </summary>
        public static string SortingPriceAscending {
            get {
                return ResourceManager.GetString("SortingPriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price descending.
        /// </summary>
        public static string SortingPriceDescending {
            get {
                return ResourceManager.GetString("SortingPriceDescending", resourceCulture);
            }
        }
    }
}
