//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.WebUI.App_LocalResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameStore.WebUI.App_LocalResources.Localization.ViewsRes", typeof(ViewsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this comment?.
        /// </summary>
        public static string CommentIndexDeleteModal {
            get {
                return ResourceManager.GetString("CommentIndexDeleteModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments for game.
        /// </summary>
        public static string CommentIndexTitle {
            get {
                return ResourceManager.GetString("CommentIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string FilteringViewModelPrice {
            get {
                return ResourceManager.GetString("FilteringViewModelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new game.
        /// </summary>
        public static string GameCreateTitle {
            get {
                return ResourceManager.GetString("GameCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string GameDetailsQuantity {
            get {
                return ResourceManager.GetString("GameDetailsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games in the store.
        /// </summary>
        public static string GameGetCount {
            get {
                return ResourceManager.GetString("GameGetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games in the store.
        /// </summary>
        public static string GameIndexTitle {
            get {
                return ResourceManager.GetString("GameIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update game.
        /// </summary>
        public static string GameUpdateTitle {
            get {
                return ResourceManager.GetString("GameUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Greet {
            get {
                return ResourceManager.GetString("Greet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibox payment.
        /// </summary>
        public static string IBoxPaymentTitle {
            get {
                return ResourceManager.GetString("IBoxPaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new .
        /// </summary>
        public static string LinkAddNew {
            get {
                return ResourceManager.GetString("LinkAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string LinkBan {
            get {
                return ResourceManager.GetString("LinkBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string LinkBuy {
            get {
                return ResourceManager.GetString("LinkBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string LinkComment {
            get {
                return ResourceManager.GetString("LinkComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string LinkComments {
            get {
                return ResourceManager.GetString("LinkComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string LinkCreate {
            get {
                return ResourceManager.GetString("LinkCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LinkDelete {
            get {
                return ResourceManager.GetString("LinkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string LinkDetails {
            get {
                return ResourceManager.GetString("LinkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string LinkDownload {
            get {
                return ResourceManager.GetString("LinkDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filters.
        /// </summary>
        public static string LinkFilter {
            get {
                return ResourceManager.GetString("LinkFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LinkLogin {
            get {
                return ResourceManager.GetString("LinkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LinkLogout {
            get {
                return ResourceManager.GetString("LinkLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make order.
        /// </summary>
        public static string LinkMakeOrder {
            get {
                return ResourceManager.GetString("LinkMakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string LinkPay {
            get {
                return ResourceManager.GetString("LinkPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LinkRegister {
            get {
                return ResourceManager.GetString("LinkRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LinkSave {
            get {
                return ResourceManager.GetString("LinkSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LinkSearch {
            get {
                return ResourceManager.GetString("LinkSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string LinkUpdate {
            get {
                return ResourceManager.GetString("LinkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string MenuBasket {
            get {
                return ResourceManager.GetString("MenuBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string MenuGames {
            get {
                return ResourceManager.GetString("MenuGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders history.
        /// </summary>
        public static string MenuOrderHistory {
            get {
                return ResourceManager.GetString("MenuOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string MenuPublishers {
            get {
                return ResourceManager.GetString("MenuPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string OrderDetailsTitle {
            get {
                return ResourceManager.GetString("OrderDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders history.
        /// </summary>
        public static string OrderHistoryTitle {
            get {
                return ResourceManager.GetString("OrderHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string OrderMakeAmount {
            get {
                return ResourceManager.GetString("OrderMakeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose payment method.
        /// </summary>
        public static string OrderMakePaymentSubtitle {
            get {
                return ResourceManager.GetString("OrderMakePaymentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string OrderMakeProduct {
            get {
                return ResourceManager.GetString("OrderMakeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderMakeQuantity {
            get {
                return ResourceManager.GetString("OrderMakeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products in your basket.
        /// </summary>
        public static string OrderMakeSubtitle {
            get {
                return ResourceManager.GetString("OrderMakeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make order.
        /// </summary>
        public static string OrderMakeTitle {
            get {
                return ResourceManager.GetString("OrderMakeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new publisher.
        /// </summary>
        public static string PublisherCreateTitle {
            get {
                return ResourceManager.GetString("PublisherCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string PublisherDetailsTitle {
            get {
                return ResourceManager.GetString("PublisherDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All publishers.
        /// </summary>
        public static string PublisherIndexTitle {
            get {
                return ResourceManager.GetString("PublisherIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update publisher.
        /// </summary>
        public static string PublisherUpdateTitle {
            get {
                return ResourceManager.GetString("PublisherUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose bun duration.
        /// </summary>
        public static string UserBanDurations {
            get {
                return ResourceManager.GetString("UserBanDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban user.
        /// </summary>
        public static string UserBanTitle {
            get {
                return ResourceManager.GetString("UserBanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of expiry.
        /// </summary>
        public static string VisaDate {
            get {
                return ResourceManager.GetString("VisaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart holder’s name.
        /// </summary>
        public static string VisaName {
            get {
                return ResourceManager.GetString("VisaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string VisaNumber {
            get {
                return ResourceManager.GetString("VisaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV2/CVC2.
        /// </summary>
        public static string VisaSecure {
            get {
                return ResourceManager.GetString("VisaSecure", resourceCulture);
            }
        }
    }
}
